micronaut.application.name=configdirector-openfeature-micronaut-sample
micronaut.server.port=3611

configdirector.server-key=fake-sample-key
configdirector.mode=streaming
configdirector.timeout=3s

logger.levels.sample.configdirector=${configdirector.log-level:INFO}
