spring.config.import=optional:file:.env[.properties]

spring.application.name=configdirector-openfeature-spring-boot-sample
server.port=3610

configdirector.server-key=${CONFIGDIRECTOR_SERVER_KEY:fake-sample-key}
configdirector.base-url=${CONFIGDIRECTOR_BASE_URL:}
configdirector.mode=${CONFIGDIRECTOR_MODE:streaming}
configdirector.timeout=${CONFIGDIRECTOR_TIMEOUT:3s}

logging.level.sample.configdirector=${CONFIGDIRECTOR_LOG_LEVEL:INFO}
