quarkus.http.port=3612
quarkus.http.test-port=0

configdirector.server-key=fake-sample-key
configdirector.mode=streaming
configdirector.timeout=3s

configdirector.log-level=INFO
quarkus.log.category."sample.configdirector".level=${configdirector.log-level}
